name: kwater
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.0
  date_format: ^2.0.2
  logger: ^1.0.0
  intl: "0.19.0"
  get_it: ^7.2.0
  sprintf: ^7.0.0
  styled_text: ^8.1.0
  flutter_dotenv: ^5.0.2
  defer_pointer: ^0.0.2
  indexed: ^0.0.8
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3
  dropdown_button2: ^2.0.0
  hovering: ^1.0.4
  syncfusion_flutter_sliders: ^26.2.10
  flutter_xlider: ^3.5.0
  gif_view: ^0.4.4
  fl_chart: ^0.69.0
  calendar_date_picker2: ^1.1.6
  proj4dart: ^2.1.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/data/
    - assets/img/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
